title: "hankhyll"
description: "I'm going to tickle your css"
baseurl: ""
url: "googre.ml"

email: email@email.com
twitter_username: tweeter
github_username: gethub

markdown: kramdown
includeFooter: true